### PR TITLE
switched to pathlib and added remote worlds

### PR DESCRIPTION
**Pull request by flying-sheep**
i may have missed a few spots where your code expects strings instead of pathlib paths.

this patch makes the code nicer in some places, and adds support for cloud saves on linux.

we’ll have to extend `get_steamdir()` to work on windows

### CODE REVIEW

**Comment by flying-sheep** [comment]
i get this traceback once my big new hardmode world is halfway rendered.

``` pytb
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "omnitool.py", line 513, in run
    p, pos = pool.apply(omnitool.gen_slice, ((self.path, pos, (w, self.header["height"]), levels, version)))
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 253, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
Exception: RLE compression error.
```

**Comment by Berserker66** [comment]
Well that's the multiprocessing module trying to raise the exception from the subprocess (raise .self_value) If your traceback ends there, then _value is likely empty and the subprocess' interpreter died before it could report. Those are among the nastiest of multiprocessing bugs, as you don't get proper debugging feedback.

This occurs once you apply this patch and not otherwise?

**Comment by flying-sheep** [comment]
sorry, missed a line.

now it’s the full TB. and i’ll check what happens without the patch

**Comment by flying-sheep** [comment]
without my patch, the same problem occurs.

**Comment by Berserker66** [comment]
RLE compression error occurs if the tile start/end points don't match - the header or a tile is a larger or smaller than expected.

What's your setup? Branch, commit, OS; how was the world last saved?

**Comment by flying-sheep** [comment]
current master (f910bdbfea1e7837ae6b1056ad69ff749d31b5a5), linux.

what do you mean “how was the world saved”?

**Comment by Berserker66** [comment]
Which exact Terraria version on which OS.

So far I only imported my windows worlds into the linux omnitool, because I can't get Terraria to run. If the linux Terraria has changes in the world format, this may well be the source of the issue.

**Comment by flying-sheep** [comment]
> Which exact Terraria version

1.3.0.7 build 6

> on which OS

still linux :wink:: Arch.

> If the linux Terraria has changes in the world format, this may well be the source of the issue.

maybe there are changes. I’ve uploaded the failing world: https://drive.google.com/file/d/0B38A9mSbgZzHa2wtdWlfODdrekE/view?usp=sharing

**Comment by Berserker66** [comment]
well in the header it's still version 155, same as windows. But there is a data change

**Comment by Berserker66** [comment]
Nevermind, was looking at a wrong export.

The world format seems the same.
Windows Terraria can load it.
And even after resaving Omnitool still can't.
Mh.
Is there anything in the world that world gen does not ever place? Painted tiles or something.
It seems to be in your base - the tile that doesn't want to be read.

**Comment by flying-sheep** [comment]
hmm, no painting, just boreal wood, granite, and marble stuff:

capture 2015-08-02 15_59_29

**Comment by Berserker66** [comment]
Should be fixed with 40a20bd7dd228ff329745b80d415731dbe371054, give that a try.

**Comment by flying-sheep** [comment]
great! the preview renders, but now i get

``` pytb
Traceback (most recent call last):
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 291, in send
    code = func.__code__
AttributeError: type object 'WorldInteraction' has no attribute '__code__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "omnitool.py", line 1277, in <module>
    run()
  File "omnitool.py", line 1047, in run
    app.run(main)
  File "/home/phil/Dev/Terraria/omnitool/pgu_override.py", line 67, in run
    self.loop()
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/app.py", line 176, in loop
    self.event(e)
  File "/home/phil/Dev/Terraria/omnitool/pgu_override.py", line 40, in event
    container.Container.event(self, sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/container.py", line 189, in event
    used = w._event(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 319, in _event
    return self.event(e)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/theme.py", line 344, in func
    return m(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/container.py", line 189, in event
    used = w._event(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 319, in _event
    return self.event(e)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/theme.py", line 344, in func
    return m(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/container.py", line 189, in event
    used = w._event(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 319, in _event
    return self.event(e)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/theme.py", line 344, in func
    return m(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/container.py", line 189, in event
    used = w._event(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 319, in _event
    return self.event(e)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/theme.py", line 344, in func
    return m(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/container.py", line 189, in event
    used = w._event(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 319, in _event
    return self.event(e)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/theme.py", line 344, in func
    return m(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/container.py", line 189, in event
    used = w._event(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 319, in _event
    return self.event(e)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/theme.py", line 344, in func
    return m(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/container.py", line 189, in event
    used = w._event(sub)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 318, in _event
    self.send(e.type,e)
  File "/home/phil/Dev/Terraria/omnitool/pgu/gui/widget.py", line 293, in send
    code = func.func_code
AttributeError: type object 'WorldInteraction' has no attribute 'func_code'
```

**Comment by Berserker66** [comment]
`WorldInteraction.__code__` is python 2 talk.

My widget.py has `if (not code in self.connects):` in line 291
you might have the wrong pgu version. 
Specifically, the entire Function:

```

    def send(self, code, event=None):
        """Send a code, event callback trigger."""
        if (not code in self.connects):
            return
        # Trigger all connected signal handlers
        for cb in self.connects[code]:
            func = cb.func
            values = list(cb.params)

            # Attempt to be compatible with previous versions of python
            try:
                code = func.__code__
            except:
                try:
                    code = func.func_code
                except:
                    # Nothing to inspect, so just call the object and hope for the best
                    func(*cb.params)
                    continue

            nargs = code.co_argcount
            names = list(code.co_varnames)[:nargs]

            # If the function is bound to an instance, remove the first argument name. Again
            # we keep compatibility with older versions of python.
            if (hasattr(func, "__self__") and hasattr(func.__self__, "__class__") or
                    hasattr(func, 'im_class')):
                names.pop(0)

            args = []
            magic = {'_event': event, '_code': code, '_widget': self}
            for name in names:
                if name in magic.keys():
                    args.append(magic[name])
                elif len(values):
                    args.append(values.pop(0))
                else:
                    break
            args.extend(values)
            func(*args)
```

**Comment by flying-sheep** [comment]
i have 0.16 from google code.

and the second traceback is interesting then (the one after “During handling of the above exception, another exception occurred:”)

**Comment by Berserker66** [comment]
The second one is just PGU beeing terribly convoluted.
Especially when it comes to events.

Your PGU is terribly outdated then. 0.16 is from 2011, 0.18 2012.
However, newer stuff is in the trunk.
Try:
`pip3 install svn+http://pgu.googlecode.com/svn/trunk/#pgu-read-only`

**Comment by Berserker66** [comment]
Unfortunately your commit broke the cache, omnitool now always generates all maps on launch.
0ad6246b25c123fcf91c7195289486686cad4d40 integrates windows steam path.

**Comment by flying-sheep** [comment]
you’re right, i need to investigate about the cache. i’m sorry i din’t say it more clearly, but i didn’t think it would do everything correctly. let’s continue in a new PR perhaps?

**Pull request merged**
